### ISSUE TITLE
While createsession getting Issuer not found issue

### ISSUE THREAD

**Issue by vnaveed** [opentok/opentok-node#208]
// Initialize OpenTok
opentok = new OpenTok(myaccountApiKey, myaccountapiSecret);

// Create a session and store it in the express app
opentok.createSession({mediaMode: 'routed'},function (err, session) {
  if (err) throw err;
  app.set('sessionId', session.sessionId);
  // We will wait on starting the app until this is done
  init();
});

getting Exception:
![Capture](https://user-images.githubusercontent.com/49260074/57754742-caf6de00-770c-11e9-930a-3be2cccb20fd.PNG)

getting Account credentials in opentok account:
![Capture1](https://user-images.githubusercontent.com/49260074/57755023-70aa4d00-770d-11e9-86d0-bc1d24f65d8e.PNG)

**Comment by a34alefeliza** [comment]
I'm getting the same issue here. Any update? Thank you, Alessandro

**Comment by msach22** [comment]
@vnaveed @a34alefeliza It seems like you're using the account API Key and Secret. Please create a project and use the API Key and Secret from the project. 

The account credentials are used for programmatically creating projects, but not for sessions, archives, etc because those are tied to a specific project.

**Comment by msach22** [comment]
Closing this ticket because this is not an issue.
